version: "3.8"
services:
  digiwallet:
    image: mongo
    container_name: digiwallet
    ports:
      - 27017:27017
    volumes:
      - mydata:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=emilygavin
      - MONGO_INITDB_ROOT_PASSWORD=password123
#  mongo-express:
#    image: mongo-express
#    container_name: digiWallet-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
#      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mydata: {}

networks:
  default:
    name: mynetwork